version: "3.9"

services:
  ssh1:
    container_name: ssh1
    build:
      context: ./servers
      args:
        USERNAME: victor
        PASSWORD: 123321
        CREATE_USER: "true"
    hostname: ssh_main
    networks:
      net:
        ipv4_address: 172.30.0.10
    ports:
      - "2222:22"
    volumes:
      - ../python_scripts/:/home/victor/scripts/
      - ssh1-ssh:/home/victor/.ssh
      - ssh1-pip:/home/victor/.local

  ssh2:
    container_name: ssh2
    build:
      context: ./servers
      args:
        USERNAME: victor
        PASSWORD: 123321
        CREATE_USER: "true"
    hostname: 3243app1
    networks:
      net:
        ipv4_address: 172.30.0.11
    ports:
      - "2223:22"

  ssh3:
    container_name: ssh3
    build:
      context: ./servers
      args:
        USERNAME: victor
        PASSWORD: 123321
        CREATE_USER: "true"
    hostname: 3243app2
    networks:
      net:
        ipv4_address: 172.30.0.12
    ports:
      - "2224:22"

  ssh4:
    container_name: ssh4
    build:
      context: ./servers
      args:
        CREATE_USER: "false"
    hostname: 6001app1
    networks:
      net:
        ipv4_address: 172.30.0.13
    ports:
      - "2225:22"

  ssh5:
    container_name: ssh5
    build:
      context: ./servers
      args:
        USERNAME: victor
        PASSWORD: 123321
        CREATE_USER: "true"
    hostname: 6001app2
    networks:
      net:
        ipv4_address: 172.30.0.14
    ports:
      - "2226:22"

  ssh6:
    container_name: ssh6
    build:
      context: ./servers
      args:
        USERNAME: victor
        PASSWORD: 123321
        CREATE_USER: "true"
    hostname: 7010app1
    networks:
      net:
        ipv4_address: 172.30.0.15
    ports:
      - "2227:22"

  ssh7:
    container_name: ssh7
    build:
      context: ./servers
      args:
        USERNAME: victor
        PASSWORD: 123321
        CREATE_USER: "true"
    hostname: 7010app2
    networks:
      net:
        ipv4_address: 172.30.0.16
    ports:
      - "2228:22"

  ssh8:
    container_name: ssh8
    build:
      context: ./servers
      args:
        USERNAME: victor
        PASSWORD: 123321
        CREATE_USER: "true"
    hostname: 8800app1
    networks:
      net:
        ipv4_address: 172.30.0.17
    ports:
      - "2229:22"

  ssh9:
    container_name: ssh9
    build:
      context: ./servers
      args:
        USERNAME: victor
        PASSWORD: pass123
        CREATE_USER: "true"
    hostname: 8800app2
    networks:
      net:
        ipv4_address: 172.30.0.18
    ports:
      - "2230:22"

  ssh10:
    container_name: ssh10
    build:
      context: ./servers
      args:
        USERNAME: victor
        PASSWORD: 123321
        CREATE_USER: "true"
    hostname: testxapp
    networks:
      net:
        ipv4_address: 172.30.0.19
    ports:
      - "2231:22"

volumes:
  ssh1-ssh:
  ssh1-pip:

networks:
  net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/24
