version: "3.9"

services:
  ssh1:
    container_name: ssh1
    build: ./servers
    networks:
      net:
        ipv4_address: 172.30.0.10
    ports:
      - "2222:22"
    volumes:
      - ../python_scripts/command_to_server:/root/scripts/command_to_server
      - ssh1-root:/root

  ssh2:
    container_name: ssh2
    build: ./servers
    networks:
      net:
        ipv4_address: 172.30.0.11
    ports:
      - "2223:22"
    volumes:
      - ssh2-root:/root
  ssh3:
    container_name: ssh3
    build: ./servers
    networks:
      net:
        ipv4_address: 172.30.0.12
    ports:
      - "2224:22"
    volumes:
      - ssh3-root:/root
networks:
  net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16

volumes:
  ssh1-root:
  ssh2-root:
  ssh3-root: